# Level 2
[meta]
name = "level2"

[start]
x = -450.0
y = -110.0

# Long ground
[[platforms]]
x = 0.0
y = -150.0
w = 1600.0
h = 40.0

# Higher platform
[[platforms]]
x = 200.0
y = -40.0
w = 200.0
h = 20.0

# Exit back to level1 (loop)
[[exits]]
x = 780.0
y = -110.0
w = 40.0
h = 80.0
next = "level1"
